import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getJwtPayload } from './api/util/JwtHelper'
import { Permission } from './api/util/Constants'
import { AccountDetails, ColorfulRequestPrintButton, Footer, Navbar } from '@/app/components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		template: '%s | PNW 3D Printing',
		default: 'Purdue Northwest 3D Printing',
	},
	description: 'Generated by create next app',
	// https://ogp.me/
	openGraph: {
	  title: "Purdue Northwest 3D Printing"
	}
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	let permission: Permission|null;
	let email: String|null;
	try {
		let jwtPayload = await getJwtPayload();
		permission = jwtPayload?.permission as Permission;
		email = jwtPayload?.email as String;
	} catch {
		permission = null;
		email = null;
	}
	
	return (
		<html lang="en" className='h-full'>
			<head>
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Coda" />
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
					rel="stylesheet" />
			</head>

			<body className={inter.className} style={{height: "100vh"}}>
				<Navbar
					links={(() => {
						if (permission == null) { return [] }
						let elements: { name: string, path: string }[] = [];
						elements.push({ name: "Orders", path: "/dashboard/user" });
						if (permission == Permission.maintainer || permission == Permission.admin) {
							elements.push({ name: "Dashboard", path: "/dashboard/maintainer" });
						}
						return elements;
					})()}

					specialElements={(() => {
						if (email) email = email.substring(0, email.lastIndexOf('@')) as String;
						else email = "Account";

						if (permission) return <> <ColorfulRequestPrintButton/> <AccountDetails permission={permission} email={email}/> </>;
						else return <AccountDetails permission={permission} email={email}/>;
					})()}
					style={{marginBottom: "0px"}}
				/>
				<main className='w-full mt-4 px-0 h-full' style={{minHeight: "90%"}}>
					{children}
				</main>
				<Footer/>
			</body>
		</html>
	)
}
