import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getJwtPayload } from './api/util/JwtHelper'
import { Permission } from './api/util/Constants'
import { AccountDetails, ColorfulRequestPrintButton, Navbar } from '@/app/components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		template: '%s | PNW 3D Printing',
		default: 'Purdue Northwest 3D Printing',
	},
	description: 'Generated by create next app',
	// https://ogp.me/
	openGraph: {
	  title: "Purdue Northwest 3D Printing"
	}
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	let permission: Permission|null;
	try {
		let jwtPayload = await getJwtPayload();
		permission = jwtPayload?.permission as Permission;
	} catch {
		permission = null;
	}
	
	return (
		<html lang="en" className='h-full'>
			<head>
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Coda" />
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
					rel="stylesheet" />
			</head>

			<body className={inter.className} style={{height: "100vh"}}>
				<main>
					<Navbar
						links={(() => {
							if (permission == null) { return [] }
							let elements: { name: string, path: string }[] = [];
							elements.push({ name: "User", path: "/dashboard/user" });
							if (permission == Permission.maintainer || permission == Permission.admin) {
								elements.push({ name: "Maintainer", path: "/dashboard/maintainer" });
							}
							if (permission == Permission.admin) {
								elements.push({ name: "Admin", path: "/dashboard/admin" });
							}
							return elements;
						})()}

						specialElements={(() => {
							if (permission != null) return <> <ColorfulRequestPrintButton/> <AccountDetails/> </>;
							else return <AccountDetails/>;
						})()}
						style={{marginBottom: "0px"}}
					/>

					<div className='w-full'>
						{children}
					</div>
				</main>
			</body>
		</html>
	)
}
